# -*- coding: utf-8 -*-
"""Wind_data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Hanifahmed/wind_analysis_project/blob/main/Wind_data_analysis.ipynb
"""

# Install required package
!pip install windrose

# ================================
# 1. Import libraries
# ================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# ================================
# 2. Load the PECD data
# ================================

url = "https://raw.githubusercontent.com/Hanifahmed/wind_analysis_project/main/data/ERA5_Wind_2024.csv"

# Read the file after the metadata section
raw = pd.read_csv(
    url,
    skiprows=52,
    header=None
)

# Split the comma-separated data
df_site = raw.iloc[:, 0].str.split(",", expand=True)

# First row contains the column names
df_site.columns = df_site.iloc[0]

# Remove the header row from the data
df_site = df_site.iloc[1:].reset_index(drop=True)

print(df_site.head())

# ================================
# 3. Select Germany
# ================================

df_site = df_site[["Date", "DE"]].copy()

# Rename columns
df_site.columns = ["time", "capacity_factor"]

print(df_site.head())

# ================================
# 4. Prepare the time information
# ================================

df_site["time"] = pd.to_datetime(df_site["time"])

# Convert capacity factor to numeric
df_site["capacity_factor"] = pd.to_numeric(
    df_site["capacity_factor"],
    errors="coerce"
)

# Set time as index
df_site = df_site.set_index("time")

print(df_site.head())

# ================================
# 5. Check the data
# ================================

print("Number of observations:")
print(len(df_site))

print("\nData type:")
print(df_site["capacity_factor"].dtype)

print("\nMissing values:")
print(df_site["capacity_factor"].isna().sum())

print("\nMinimum capacity factor:")
print(df_site["capacity_factor"].min())

print("\nMaximum capacity factor:")
print(df_site["capacity_factor"].max())

# ================================
# 6. Convert capacity factor to %
# ================================

df_site["capacity_factor_percent"] = (
    df_site["capacity_factor"] * 100
)

print(df_site.head())

# ================================
# 7. Capacity factor statistics
# ================================

print(
    df_site["capacity_factor_percent"].describe()
)

# ================================
# 8. Annual average capacity factor
# ================================

annual_cf = df_site["capacity_factor"].mean()

print(
    "Average capacity factor:",
    round(annual_cf * 100, 2),
    "%"
)

# ================================
# 9. Capacity factor distribution
# ================================

plt.figure(figsize=(8, 5))

plt.hist(
    df_site["capacity_factor_percent"],
    bins=30,
    edgecolor="black"
)

plt.xlabel("Capacity factor (%)")
plt.ylabel("Number of hours")
plt.title("Hourly Wind Capacity Factor Distribution — Germany, 2024")

plt.show()

# ================================
# 10. Monthly capacity factor
# ================================

monthly_cf = (
    df_site["capacity_factor"]
    .groupby(df_site.index.month)
    .mean()
)

monthly_cf_percent = monthly_cf * 100

plt.figure(figsize=(8, 5))

plt.plot(
    monthly_cf_percent.index,
    monthly_cf_percent.values,
    marker="o"
)

plt.xlabel("Month")
plt.ylabel("Average capacity factor (%)")
plt.title("Monthly Average Wind Capacity Factor — Germany, 2024")

plt.xticks(range(1, 13))

plt.grid(alpha=0.3)

plt.show()

# ================================
# 11. Seasonal capacity factor
# ================================

df_site["season"] = df_site.index.month.map({
    12: "Winter",
    1: "Winter",
    2: "Winter",

    3: "Spring",
    4: "Spring",
    5: "Spring",

    6: "Summer",
    7: "Summer",
    8: "Summer",

    9: "Autumn",
    10: "Autumn",
    11: "Autumn"
})

seasonal_cf = (
    df_site
    .groupby("season")["capacity_factor"]
    .mean()
    * 100
)

print(seasonal_cf)
# ================================
# capacity factor plot
# ================================
plt.figure(figsize=(7, 5))

seasonal_cf.plot(
    kind="bar"
)

plt.xlabel("Season")
plt.ylabel("Average capacity factor (%)")
plt.title("Seasonal Wind Capacity Factor — Germany, 2024")

plt.xticks(rotation=0)

plt.show()

# ================================
# 12. Capacity factor duration curve
# ================================

sorted_cf = np.sort(
    df_site["capacity_factor_percent"]
)[::-1]

hours = np.arange(
    1,
    len(sorted_cf) + 1
)

plt.figure(figsize=(8, 5))

plt.plot(
    hours,
    sorted_cf
)

plt.xlabel("Hours")
plt.ylabel("Capacity factor (%)")
plt.title("Wind Capacity Factor Duration Curve — Germany, 2024")

plt.grid(alpha=0.3)

plt.show()

# ================================
# 13. Simple AEP calculation
# ================================

installed_capacity = 100  # MW
hours_per_year = 8760

AEP = (
    annual_cf
    * installed_capacity
    * hours_per_year
)

print(
    "Assumed installed capacity:",
    installed_capacity,
    "MW"
)

print(
    "Estimated annual energy production:",
    round(AEP, 1),
    "MWh/year"
)

print(
    "Estimated annual energy production:",
    round(AEP / 1000, 2),
    "GWh/year"
)